databases:
  - name: Iromemo
    databaseName: iromemo
    user: iromemo_user
    region: singapore

services:
  - type: web
    name: Iromemo
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: LANG
        value: en_US.UTF-8
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
