# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: iromemo_backend_development

production:
  <<: *default
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false
  url: <%= ENV['DATABASE_URL'] %>
